Numpy

In [ ]:
#numpy

#array
#matrices
#masked arrays
#elemets should be of same data type

#arange---gives #s in a sequence
#random--from 0 to 1 random #s generates

In [2]:
#!pip install numpy

import numpy as np

#create numpy array
a=np.array([1,2,3])   #list pass
print(a)

[1 2 3]


In [3]:
type(a)

numpy.ndarray

In [ ]:
#1D --- vector
#2D --- matrix
#3D --- Tensor

In [4]:
np.array([1,2,3],dtype=int)  #or float

array([1, 2, 3])

In [5]:
#arange ---- like range function no difference
np.arange(1,11)   #or(11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(1,11,2)  #step 2 means skip 1 item and give next/2nd

array([1, 3, 5, 7, 9])

In [ ]:
#Reshape
np.arange(1,11)   #1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#convert 1D to 2D

np.arange(1,11).reshape(5,2)  #5*2=10 items total

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#3D array

np.arange(1,11).reshape(5,1,2)  #3D array  #product of reshape numbers should equal total items of the array. 5*1*2=10

array([[[ 1,  2]],

       [[ 3,  4]],

       [[ 5,  6]],

       [[ 7,  8]],

       [[ 9, 10]]])

In [ ]:
#4D array

np.arange(16).reshape(2,2,2,2)  #2*2*2*2=16

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
#all items 1s---used in neural networks-to initiate values to weights

np.ones((3,4))   #2D shape(3,4) --provide sep. brackets for shape

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#all items 0s

np.zeros((3,4))  #2D all items 0s

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#if you want to initiate by random numbers
#between 0 and 1 numbers generate in shape 2D (3,4)

np.random.random((3,4))

array([[0.20175809, 0.38647358, 0.44138088, 0.32497907],
       [0.45149967, 0.26600204, 0.04329446, 0.27611036],
       [0.50428059, 0.26246398, 0.16456426, 0.06652207]])

In [16]:
#if you want to generate numbers at equal distance
#used to visualize ML algorithm results by plotting we use this.

np.linspace(-10,10,10)  #generate in range -10 to 10 total 10 items last one is # of items not steps


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.identity(3)   #indentity matrix create

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
a1=np.arange(10,dtype=np.int32).reshape(10,)  #1D as shape(10,)
a2=np.arange(12,dtype=float).reshape(3,4)      #2D 
a3=np.arange(8).reshape(2,2,2)                #3D

In [22]:
print(a3.shape)
print(a3.ndim)
print(a3)

#(2,2,2)---- 1st 2 refers how many items in this case 2 items--2 - 2D arrays
            #2nd and 3rd 2s tells us the shape of those 2- 2D arrays. shape 2,2
            
#2 items of shape 2D-- this 3D array made up of 2 - 2D arrays and each of the 2D array shape is 2,2


(2, 2, 2)
3
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [24]:
print(a1.ndim)
print(a2.ndim)

1
2


In [ ]:
#size
a3.size   #number of items  2*2*2=8

8

In [29]:
#itemsize --- how much memory size used by an array
print(a3.itemsize)  #a3 taking 8 bytes size
print(a1.itemsize)


8
4


In [31]:
#astype
#changing data type

a3.astype(np.int32)   #default int64 convert to int32
print(a3.itemsize)

8


Array Operations

In [ ]:
#scalar operation
#vector operation

In [ ]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)     #both 2D arrays bcz shape (a,b)

#scalar operations---- (* / + -)
print(a1*2)    #here 2 is a scalar

#relational operation----- (> < etc)
print(a2>15)   #truefasle

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [6]:
#vector/tensor operations ---  2 arrays operation
#condition-- shape of both arrays should be same.
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
#Array functions
a1=np.random.random((3,3))   #it generates random #s from 0 to 1. Shape 2D
a1=np.round(a1*100)   #random #s from 0 to 1 multiped by 100
a1


array([[72., 38., 44.],
       [41., 99., 59.],
       [ 6., 99., 67.]])

In [11]:
#max/min/sum/prod
print(np.max(a1))

print(np.sum(a1)) #every item added

print(np.prod(a1))

#find min of each row
print(np.min(a1,axis=1))   #1 means row and 0--column

#column wise max find
print(np.max(a1,axis=0))


99.0
525.0
1147363632657792.0
[38. 41.  6.]
[72. 99. 67.]


In [ ]:
#mean/median/standardDev/Var
np.mean(a1,axis=1) #each row sep. mean find

array([51.33333333, 66.33333333, 57.33333333])

In [ ]:
#trignometic functions
#np.sin()

#dot product--- used in linear algebra
#condition for dot product--- 1st array/matrix column and second array rows should equal
#let shape (3,4) (4,3) --resultant shape (3,3)


#log and exponents
np.log(a1)
np.exp()



In [16]:
#round/flooe/ceil
print(np.random.random((2,3))*100)  #0 to 1 converted to 0 to 100

#to get integer part only use round
print(np.round(np.random.random((2,3))*100))

#to get let 6 from 6.9 only before decimal part ----use floor
print(np.floor(np.random.random((2,3))*100))

#to get 7 from 6.1--- use ceil
print(np.ceil(np.random.random((2,3))*100))


[[17.8086472  48.76372371 56.59342847]
 [25.04444433 12.46280434 59.59326986]]
[[26. 12. 67.]
 [20.  5. 21.]]
[[39. 41. 11.]
 [95. 54. 67.]]
[[11. 56. 86.]
 [21. 99. 53.]]


In [9]:
#indexing and slicing
#fetching items from a mumpy array using indexing
a1=np.arange(10)  #1D
a2=np.arange(12).reshape(3,4)  #2D
a3=np.arange(8).reshape(2,2,2)    #3D


In [ ]:
print(a1)  #1D array

#indexing 1D array--fetching items
print(a1[-1])  #last item returns

print(a1[0])   #returns 1st item at index 0

[0 1 2 3 4 5 6 7 8 9]
9
0


In [ ]:
print(a2)   #2D array   shape---(3,4)  column/row index starts with 0 1 2...

#a2[rowindex#, columnindex#]
print(a2[1,2])   #at row index# 1 and column index # 2 we have 6


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6


In [26]:
print(a3)  #3D shape(2,2,2)-- 1st position 2 indicates how many 2Ds
           #so here 2 - 2D arrays of each shape (2,2) last 2 position 2s represnt shape of that 2 - 2D arrays
           #as 3D is made up of 2Ds.. and 2D made up of 1Ds

#lets fetch 5
#a3[1st select which 2D of the 2-2Ds using index 0,1    ,    now select row index      ,    column index od that selected 2D]

print(a3[1,0,1])


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5


In [ ]:
#4D array --fetch items---made up of 3 - 3Ds

#five 4 numbers   a[a,b,c,d]
#1st select which 3D is the number presrent using 0 1 or 2
#select which 2D the # is present of the above selected 3D using 0,1
#select row index of that 2D   ,COMA  SELECT column index of that 2D

In [6]:
#slicing --- fetch mltiple items
print(a1)

#fetch 2,3,4 from above 1D array
a1[2:5]

[0 1 2 3 4 5 6 7 8 9]


array([2, 3, 4])

In [ ]:
print(a2)

#1st full row fetch
a2[0,:]   #it will fetch 0 # row and all columns : means all

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 1, 2, 3])

In [ ]:
#3rd column select
a2[:,2]   #row#,column#

array([ 2,  6, 10])

In [ ]:
#fetch 5 6 and 9 10
a2[1:,1:3]   #1:3 means 1 2 will come 3 will not come.
              #we used 1: because only 1 row left so i said return everything from 1 till end

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
# fetch 0 3 and 8 11
a2[::2,::3]   #frist row then jump then last row  ,  first column then jump then last column

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
print(a2)

# fetch 1 3 and 9 11
a2[::2,1::2]  #1st row jump and last row , 2nd column jump and 3rd column

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 1,  3],
       [ 9, 11]])

In [17]:
#fetch 4 and 7
a2[1,::3]        #2nd row , 1st column and last column

array([4, 7])

In [ ]:
#3D case   consists of 2Ds
a3=np.arange(8).reshape(2,2,2)    #3D

In [ ]:
print(a3)   #this 3d array consists of 2 , 2D arrays

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [6]:
#fetch 2nd wala 2D array
#print(a3)
a3[1]

array([[4, 5],
       [6, 7]])

In [ ]:
b3 = np.arange(27).reshape(3,3,3)   #consists of 3 , 2d arrays
b3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
#fetch 1st and last 3rd wala 2Ds
b3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Iterating  - loop run on your numpy array

In [14]:
#loop on 1D array
print(a1)

for i in a1:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [ ]:
#loop on 2D array
print(a2)

for i in a2:
    print (i)         #it will print each whole row


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
#loop on 3D array
print(a3)

#for 3D each of the 2d will get printed
for i in a3:
    print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [27]:
#nditer  -Any dimention brings in 1D

#convert 3D to 1D then print all items
print(a3)

for i in np.nditer(a3):
    print(i)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
0
1
2
3
4
5
6
7


In [ ]:
#reshaping

#1 reshape
#2 ranspose --row to col/col to rows
#3 Ravel or flatten()   --both converts to 1D

In [ ]:
#transpose
print(a2)

np.transpose(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [29]:
#ravel or flatten()
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

stacking -- vertical and horizontal stacking 
            vstacking    hstacking

In [ ]:
#2 or more arrays combine
#two ways  --- horizontally or vertically
#let 2 arrays with shape 2x2 and 2x2
#after stack 2x4  ---for horizontally stack--cols increased
#for vertical -4x2

#np.hstack(a4,a5)

splitting

horizontally  hsplit
vertically    vsplit


In [ ]:
#splitiing   --opposite of stacking

#np.hhsplit(a4,2)   #split a4 into 2 equal parts

Advanced Numpy

In [ ]:
#Advanced indexing
a=np.arange(12).reshape(4,3)   #2D
print(a)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#normal indexing
print(a[1,2])

print(" ")   #used just to get gap

print(a[1:3,1:3])

5
 
[[4 5]
 [7 8]]


In [ ]:
#fancy indexing   --- simply provide list and inside all the required items to be fetched positions.

#normal indexing --- let i want to fetch 1st and 3rd row--- it is fetcable as a pattern is there
print(a)

print(" ")

a[::2]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 


array([[0, 1, 2],
       [6, 7, 8]])

In [10]:
#what if no pattern is there.
#lets fetch 1st 3rd 4th row --- no pattern so normal indexing will not work so use fancy indexing
#pass list inside square brackets -- index positions provide inside.

a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
a=np.arange(24).reshape(6,4)

#fetch 1st 3rd 4th 6th rows
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [14]:
#to fetch columns
print(a)

print(" ")

a[:,[0,2,3]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
 


array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
#boolean indexing--- helps in data filtering
#picking items on the basis of a condition

#like picking only even ones
#or divisibe by 5

a=np.random.randint(1,100,24).reshape(6,4)         #generating random #s from 1 to 100 total 24 in 2D shape 6x4
print(a)

[[45 28 63 20]
 [72 92 27  6]
 [42 49 90 69]
 [12  6 42 84]
 [95 80 53 63]
 [64 68 74  7]]


In [17]:
#boolean indexing
#pick ones > 50
a>50

array([[False, False,  True, False],
       [ True,  True, False, False],
       [False, False,  True,  True],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [ ]:
a[a%2==0]   #even #s

array([28, 20, 72, 92,  6, 42, 90, 12,  6, 42, 84, 80, 64, 68, 74],
      dtype=int32)

In [ ]:
# 2 logics together
a[(a>50)&(a%2==0)]   #when dealing with boolens use & sign not AND

array([72, 92, 90, 84, 80, 64, 68, 74], dtype=int32)

Numpy tricks

In [5]:
#working with missing values     np.nan
#dealing missings in array

a=np.array([1,2,3,4,np.nan,6])

#boolean indexing use to remove missing
a[np.isnan(a)]

array([nan])

In [6]:
a[~np.isnan(a)]     #not operator used to get all values except isnan

array([1., 2., 3., 4., 6.])

In [6]:
#np.sort       returns array
import numpy as np
a=np.random.randint(1,100,15)                     #1d
b=np.random.randint(1,100,24).reshape(6,4)        #2d

print(a)

print("")

print(b)


[49 31 69 93 21 68 18 77 18 47  7  7  1 16  6]

[[11 93 82 97]
 [76 14 39 40]
 [92 33 24 40]
 [41 31 43 35]
 [84 35 87 50]
 [ 4 65 34 32]]


In [19]:
print(np.sort(a,axis=-1,kind=None,order=None))

print(np.sort(a,axis=0,kind=None,order=None))   #column wise sort

print(np.sort(a)[::-1])    #in decrease order sort

[18 23 27 32 52 61 63 76 80 83 84 85 89 97 99]
[18 23 27 32 52 61 63 76 80 83 84 85 89 97 99]
[99 97 89 85 84 83 80 76 63 61 52 32 27 23 18]


In [21]:
#np.append ---appends values along the ais at end of array
print(a)

print("")

print(np.append(a,200))

[84 63 23 32 76 80 85 61 18 83 27 97 89 52 99]

[ 84  63  23  32  76  80  85  61  18  83  27  97  89  52  99 200]


In [24]:
#in case of 2d new column add
print(b)

print("")

print(np.ones((3,4)))  #2darray with all values 1s  --- this is just for understanding not used anywhere

print("")

print(np.append(b,np.ones((b.shape[0],1)),axis=1))     #new column with all values 1 added at end

[[58 97 34 26]
 [21 47 97 87]
 [72 83 67 90]
 [70 85 22 55]
 [43  3 73 12]
 [75 51 15 29]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[58. 97. 34. 26.  1.]
 [21. 47. 97. 87.  1.]
 [72. 83. 67. 90.  1.]
 [70. 85. 22. 55.  1.]
 [43.  3. 73. 12.  1.]
 [75. 51. 15. 29.  1.]]


In [ ]:
#np.unique    finds unique from array
#np.unique(e)

In [36]:
#np.expand_dims    expend dimensions   1d convert to 2d   --- 2d convert to 3d   so on
np.expand_dims(a,axis=0)

array([[84, 63, 23, 32, 76, 80, 85, 61, 18, 83, 27, 97, 89, 52, 99]],
      dtype=int32)

In [38]:
#np.where   returns index positions
np.where(a>50)

#np.where(condition,true,false)

#replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0, 23, 32,  0,  0,  0,  0, 18,  0, 27,  0,  0,  0,  0],
      dtype=int32)

In [46]:
#np.argmax     returns indices of max element of array in a particular axis
print(b)

print(".......................")

print(np.argmax(a))

print(np.argmax(b,axis=0))


#argmin

[[58 97 34 26]
 [21 47 97 87]
 [72 83 67 90]
 [70 85 22 55]
 [43  3 73 12]
 [75 51 15 29]]
.......................
14
[5 0 1 2]


In [35]:
#np.concatenate           concat. a seq. of arrays along an existing axis   similiar to stacking you can use either of the both
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)

print(d)

print("")

#by row concat
print(np.concatenate((c,d),axis=0))

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
#np.cumsum     cumulative sum of array elements over a given axis
print(a)

print(np.cumsum(a))

[49 31 69 93 21 68 18 77 18 47  7  7  1 16  6]
[ 49  80 149 242 263 331 349 426 444 491 498 505 506 522 528]


In [10]:
print(b)

#in case of 2d axis give.
np.cumsum(b,axis=0)

[[11 93 82 97]
 [76 14 39 40]
 [92 33 24 40]
 [41 31 43 35]
 [84 35 87 50]
 [ 4 65 34 32]]


array([[ 11,  93,  82,  97],
       [ 87, 107, 121, 137],
       [179, 140, 145, 177],
       [220, 171, 188, 212],
       [304, 206, 275, 262],
       [308, 271, 309, 294]])

In [13]:
#np.percentile
print(np.percentile(a,100))   #will give the max numb

#max marks in whole class let 93 so 93 will be 100 percentile bcz all others are less than 93.

print(np.percentile(a,0))   #min #

#medium center #    where half that # are above and other half below that number
np.percentile(a,50)

93.0
1.0


np.float64(21.0)

In [ ]:
#np.histogram    tells frequency count in an array
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

# from 0 to 10   how many items??   from 10 to 20 ??  from 20 to 30 and on...

(array([4, 3, 1, 1, 2, 0, 2, 1, 0, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [ ]:
#np.corrcoef        returns pearson    -1 to 1
#np.corrcoef(a,b)

In [ ]:
#np.isin
#a[np.isin(a,items)]    #search items elements in array a

In [ ]:
#np.flip   #shape will remain same but items will get fliped not sort but flip   11 53 28      ....    28 53 11

In [ ]:
#np.clip   used to clip limit the values in an array
np.clip(a,a_min=25,a_max=75)

#all items less than 25 are replaced with 25 and all items >75 are replaced with 75

array([49, 31, 69, 75, 25, 68, 25, 75, 25, 47, 25, 25, 25, 25, 25],
      dtype=int32)

Broadcasting rules
describes how munpy treats arrays with different shapes during arithmetic operations

In [ ]:
#same shapes arrays can be added
#different shapes arrays can also be added how? broadcasting concept

#smaller array is broadcasted across larger array so that they have compatible shapes
#smaller array will repeat/broadcast.

#numpy handles it internally we dont need to instruct it. we learning broadcasting just to know the concept what internally happens.

#       1 1 1           0 1 2
#       1 1 1     +
#       1 1 1

#the small array will repeat  

#       1 1 1           0 1 2
#       1 1 1     +     0 1 2  repeat
#       1 1 1           0 1 2  repeat

#solution

#        1 2 3
#        1 2 3
#        1 2 3





In [ ]:
#broadcasting rules
#3 rules

#1 make the two arrays have the same number of dimensions 
#if one is 2d and one 1d first bring both in same dimension make 1d to 2d
#add new dimension with size 1 to the head of array with smaller dimension
#    (3,) 1d     (3,2) 2d  
#    (1,3)

#    (3,3,3)   (3,)         
#    (1,1,3)

#2 rule 2.....
#make each dimension of the two arrays the same

#3 rule 3.....
#if there is dimension where size is not 1 in either of the two arrays it cant be broadcasted and an error is raised.
# pick the one which is 1 and strech it equal to the bigger

# (3,3)    (3,)       1,3   rule 1
#                     3,3   rule 2   strech the 1 equal to the bigger one.


#in short first make dimension equal by adding 1 to head of smaller one.
#then strech dimension of smaller array equal to bigger one.

# (5,3)  (3,1)     already both 2d same so rule 1 already satisfied
# strech the 1 equal to the other array.   so  (5,3)  (3,3)     
#  1 is important in any one of the two arrays otherwise error